"""Initial schema — all SentinelleRx tables, enums, and indexes.

This baseline revision provisions required PostgreSQL extensions and then
materializes the full model metadata (reference, transactional, ML, decision,
and ops tables). Subsequent revisions should be hand-written or autogenerated
as incremental deltas from here.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-18
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.core.database import Base

# Import models so every table is registered on Base.metadata.
import app.models  # noqa: F401

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    if is_pg:
        # Extensions (idempotent). pg_trgm accelerates medication search.
        # PostGIS is optional now (geometry is stored as GeoJSON) but harmless.
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    Base.metadata.create_all(bind=bind)

    if is_pg:
        # Trigram indexes for fast fuzzy medication search (PostgreSQL only).
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_medications_dci_trgm "
            "ON medications USING gin (dci gin_trgm_ops)"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_medications_brand_trgm "
            "ON medications USING gin (brand_name gin_trgm_ops)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
