apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinellerx
resources:
  - namespace.yaml
  - config.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - scoring-cronjob.yaml
  - ingress.yaml
  - networkpolicy.yaml
